# Generated by Django 5.1.5 on 2025-01-22 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(db_index=True, max_length=10, verbose_name='номер стола')),
                ('status', models.CharField(choices=[('В ожидании', 'Pending'), ('Готово', 'Ready'), ('Оплачено', 'Paid')], db_index=True, default='В ожидании', max_length=12, verbose_name='статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время и дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время и дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
