# Generated by Django 5.1.5 on 2025-01-24 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть больше или равно 1.')], verbose_name='количество'),
        ),
    ]
